// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJQQ7Wg_Z8ffefJZIJwcqeog-hnHjTdY',
    appId: '1:1024423680478:web:cf7c723a09f6c9b99a254f',
    messagingSenderId: '1024423680478',
    projectId: 'car-rental-app-bec12',
    authDomain: 'car-rental-app-bec12.firebaseapp.com',
    storageBucket: 'car-rental-app-bec12.firebasestorage.app',
    measurementId: 'G-HHN38Q1281',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq9WuB1LwN2LXgzNc_4hjPnREFEjBHYPc',
    appId: '1:1024423680478:android:65c346378b88e3719a254f',
    messagingSenderId: '1024423680478',
    projectId: 'car-rental-app-bec12',
    storageBucket: 'car-rental-app-bec12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFakW7MS-8IsCiQ_1z5zU8HcPAjgse3ts',
    appId: '1:1024423680478:ios:0b835e233b90a9649a254f',
    messagingSenderId: '1024423680478',
    projectId: 'car-rental-app-bec12',
    storageBucket: 'car-rental-app-bec12.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFakW7MS-8IsCiQ_1z5zU8HcPAjgse3ts',
    appId: '1:1024423680478:ios:0b835e233b90a9649a254f',
    messagingSenderId: '1024423680478',
    projectId: 'car-rental-app-bec12',
    storageBucket: 'car-rental-app-bec12.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaJQQ7Wg_Z8ffefJZIJwcqeog-hnHjTdY',
    appId: '1:1024423680478:web:5bc233c0aaa494999a254f',
    messagingSenderId: '1024423680478',
    projectId: 'car-rental-app-bec12',
    authDomain: 'car-rental-app-bec12.firebaseapp.com',
    storageBucket: 'car-rental-app-bec12.firebasestorage.app',
    measurementId: 'G-DTCQPZE5MC',
  );
}
